# scons build file for cMsg C library
Import('env', 'libInstallDir', 'incInstallDir', 'archIncInstallDir', 'debugSuffix')

# Files to compile
fileList = Glob('*.c',  strings=True)

# Headers to install
headerList = Glob('cMsg*.h',  strings=True)

env.AppendUnique(CPPPATH = ['.', '#src/regexp'])
cmsgLib = env.SharedLibrary(target = 'cmsg'+debugSuffix, source = fileList)

if 'install' in COMMAND_LINE_TARGETS:
    env.Alias("install", env.Install(target = [incInstallDir, archIncInstallDir], source = headerList))
    env.Alias("install", env.Install(target = libInstallDir, source = cmsgLib))
