# scons build file for cmsg
Import('env', 'libDir', 'incDir', 'tarfile', 'debugSuffix')

fileList = ['cMsg.c',
            'cMsgCompoundPayload.c',
            'cMsgDomain.c',
            'cMsgDomainListenThread.c',
            'cMsgDomainUtil.c',
            'cMsgMatching.c',
            'cMsgNetwork.c',
            'encode.c',
            'fileDomain.c',
            'hash.c',
            'rcDomain.c',
            'rcDomainListenThread.c',
            'rwlock.c',
            'sunConcurrency.c']

env.AppendUnique(CPPPATH = ['.', '#src/regexp'])
cmsgLib = env.SharedLibrary(target = 'cmsg'+debugSuffix, source = fileList)

env.Alias("install", env.Install(target = incDir, source = 'cMsg.h'))
env.Alias("install", env.Install(target = libDir, source = cmsgLib))
