cMsg Messaging System: cmsg::cMsg Class Reference
cmsg::cMsg Class Reference
Wraps most cMsg C calls, provides main functionality.
#include <cMsg.hxx>
Public Member Functions
cMsg (const string &UDL, const string &name, const string &descr)
Constructor for cMsg system object.
virtual ~cMsg (void)
Destructor disconects from cMsg system.
virtual void connect ()
Connects to cMsg system.
virtual void disconnect (void)
Disconnects from cMsg system.
virtual void send (cMsgMessage &msg)
Sends message.
virtual void send (cMsgMessage *msg)
Sends message.
virtual int syncSend (cMsgMessage &msg, const struct timespec *timeout=NULL)
Synchronously sends message.
virtual int syncSend (cMsgMessage *msg, const struct timespec *timeout=NULL)
Synchronously sends message.
virtual void * subscribe (const string &subject, const string &type, cMsgCallback *cb, void *userArg, const cMsgSubscriptionConfig *cfg=NULL)
Subscribes to subject,type and specifies callback, userArg.
virtual void * subscribe (const string &subject, const string &type, cMsgCallback &cb, void *userArg, const cMsgSubscriptionConfig *cfg=NULL)
Subscribes to subject,type and specifies callback,userArg.
virtual void unsubscribe (void *handle)
Unsubscribes.
virtual void subscriptionPause (void *handle)
Pause delivery of messages to the given subscription's callback.
virtual void subscriptionResume (void *handle)
Resume delivery of messages to the given subscription's callback if paused.
virtual void subscriptionQueueClear (void *handle)
Clear all messages from the given subscription callback's queue.
virtual int subscriptionQueueCount (void *handle)
Return the number of messages currently in the given subscription callback's queue.
virtual bool subscriptionQueueIsFull (void *handle)
Returns whether the given subscription callback's queue is full (true) or not.
virtual int subscriptionMessagesTotal (void *handle)
Return the total number of messages passed to the given subscription's callback.
virtual cMsgMessage * sendAndGet (cMsgMessage &sendMsg, const struct timespec *timeout=NULL)
Sends message and gets reply.
virtual cMsgMessage * sendAndGet (cMsgMessage *sendMsg, const struct timespec *timeout=NULL)
Sends message and gets reply.
virtual cMsgMessage * subscribeAndGet (const string &subject, const string &type, const struct timespec *timeout=NULL)
Subscribes to subject/type, returns one matching message, then unsubscribes.
virtual void flush (const struct timespec *timeout=NULL)
Flushes outgoing message queues.
virtual void start (void)
Enables delivery of messages to callbacks.
virtual void stop (void)
Disables delivery of messages to callbacks.
virtual void setUDL (const string &udl)
Sets the connection UDL.
virtual string getUDL (void) const
Gets connection UDL.
virtual string getCurrentUDL (void) const
Gets UDL of the current connection, "null" if no connection.
virtual string getName (void) const
Gets connection name.
virtual string getDescription (void) const
Gets connection description.
virtual bool isConnected (void) const
True if connected.
virtual bool isReceiving (void) const
True if receiving messages.
virtual void setShutdownHandler (cMsgShutdownHandler *handler, void *userArg)
Sets shutdown handler.
virtual void shutdownClients (const string &client, int flag)
Shuts down a client.
virtual void shutdownServers (const string &server, int flag)
Shuts down a server.
virtual cMsgMessage * monitor (const string &monString)
Returns domain-dependent monitoring information.
virtual void setMonitoringString (const string &monString)
Sets monitoring string.
Detailed Description
Wraps most cMsg C calls, provides main functionality.
Definition at line 363 of file cMsg.hxx.
Constructor & Destructor Documentation
cMsg()
cMsg::cMsg (const string & UDL, const string & name, const string & descr)
Constructor for cMsg system object.
Parameters
UDL Connection UDL
name Name
descr Description
Definition at line 1642 of file cMsgWrapper.cc.
~cMsg()
cMsg::~cMsg (void) virtual
Destructor disconects from cMsg system.
Exceptions
cMsgException
Definition at line 1654 of file cMsgWrapper.cc.
References disconnect().
Member Function Documentation
connect()
void cMsg::connect (void) virtual
Connects to cMsg system.
If a connection has already been made, a reconnection will be attempted. In a reconnection, if there is no current connection one will be made. If there is a current, healthy connection and if the UDL to which a connection attempt will be made is identical to the currentUDL, nothing is done. If there is a current, healthy connection, and if the UDL to which a connection attempt will be made is different from the current UDL, the current connection will be disconnected and a new connection attempted with the new UDL.
Exceptions
cMsgException
Definition at line 1673 of file cMsgWrapper.cc.
disconnect()
void cMsg::disconnect (void) virtual
Disconnects from cMsg system.
Exceptions
cMsgException
Definition at line 1699 of file cMsgWrapper.cc.
Referenced by ~cMsg().
flush()
void cMsg::flush (const struct timespec * timeout = NULL) virtual
Flushes outgoing message queues.
Parameters
timeout Timeout
Exceptions
cMsgException
Definition at line 2131 of file cMsgWrapper.cc.
getCurrentUDL()
string cMsg::getCurrentUDL (void) const virtual
Gets UDL of the current connection, "null" if no connection.
Returns
UDL of current connection
Exceptions
cMsgException
Definition at line 2248 of file cMsgWrapper.cc.
getDescription()
string cMsg::getDescription (void) const virtual
Gets connection description.
Returns
Description
Definition at line 2189 of file cMsgWrapper.cc.
getName()
string cMsg::getName (void) const virtual
Gets connection name.
Returns
Name
Definition at line 2202 of file cMsgWrapper.cc.
getUDL()
string cMsg::getUDL (void) const virtual
Gets connection UDL.
Returns
UDL
Definition at line 2215 of file cMsgWrapper.cc.
isConnected()
bool cMsg::isConnected (void) const virtual
True if connected.
Returns
True if connected
Exceptions
cMsgException
Definition at line 2273 of file cMsgWrapper.cc.
isReceiving()
bool cMsg::isReceiving (void) const virtual
True if receiving messages.
Returns
True if receiving messages
Exceptions
cMsgException
Definition at line 2295 of file cMsgWrapper.cc.
monitor()
cMsgMessage * cMsg::monitor (const string & monString) virtual
Returns domain-dependent monitoring information.
Parameters
monString Monitoring request string
Returns
Message containing monitoring information in text field
Exceptions
cMsgException
Definition at line 2384 of file cMsgWrapper.cc.
send() [1/2]
void cMsg::send (cMsgMessage & msg) virtual
Sends message.
Parameters
msg Message to send
Exceptions
cMsgException
Definition at line 1718 of file cMsgWrapper.cc.
References cmsg::cMsgMessage::myMsgPointer.
Referenced by send().
send() [2/2]
void cMsg::send (cMsgMessage * msg) virtual
Sends message.
Parameters
msg Message to send
Exceptions
cMsgException
Definition at line 1739 of file cMsgWrapper.cc.
References send().
sendAndGet() [1/2]
cMsgMessage * cMsg::sendAndGet (cMsgMessage & sendMsg, const struct timespec * timeout = NULL) virtual
Sends message and gets reply.
Parameters
sendMsg Message to send
timeout Timeout
Returns
Reply message
Exceptions
cMsgException
Definition at line 2050 of file cMsgWrapper.cc.
References cmsg::cMsgMessage::myMsgPointer.
sendAndGet() [2/2]
cMsgMessage * cMsg::sendAndGet (cMsgMessage * sendMsg, const struct timespec * timeout = NULL) virtual
Sends message and gets reply.
Parameters
sendMsg Message to send
timeout Timeout
Returns
Reply message
Exceptions
cMsgException
Definition at line 2078 of file cMsgWrapper.cc.
References cmsg::cMsgMessage::myMsgPointer.
setMonitoringString()
void cMsg::setMonitoringString (const string & monString) virtual
Sets monitoring string.
Parameters
monString Monitoring string
Exceptions
cMsgException
Definition at line 2410 of file cMsgWrapper.cc.
setShutdownHandler()
void cMsg::setShutdownHandler (cMsgShutdownHandler * handler, void * userArg) virtual
Sets shutdown handler.
Parameters
handler Shutdown handler
userArg Arg passed to handler upon shutdown
Exceptions
cMsgException
Definition at line 2318 of file cMsgWrapper.cc.
setUDL()
void cMsg::setUDL (const string & udl) virtual
Sets the connection UDL.
Any subsequent failovers or reconnects will use the new UDL.
Parameters
udl new UDL
Exceptions
cMsgException
Definition at line 2230 of file cMsgWrapper.cc.
shutdownClients()
void cMsg::shutdownClients (const string & client, int flag) virtual
Shuts down a client.
Parameters
client The client
flag Shutdown flag
Exceptions
cMsgException
Definition at line 2340 of file cMsgWrapper.cc.
shutdownServers()
void cMsg::shutdownServers (const string & server, int flag) virtual
Shuts down a server.
Parameters
server The server
flag Shutdown flag
Exceptions
cMsgException
Definition at line 2362 of file cMsgWrapper.cc.
start()
void cMsg::start (void) virtual
Enables delivery of messages to callbacks.
Exceptions
cMsgException
Definition at line 2150 of file cMsgWrapper.cc.
stop()
void cMsg::stop (void) virtual
Disables delivery of messages to callbacks.
Exceptions
cMsgException
Definition at line 2169 of file cMsgWrapper.cc.
subscribe() [1/2]
void * cMsg::subscribe (const string & subject, const string & type, cMsgCallback & cb, void * userArg, const cMsgSubscriptionConfig * cfg = NULL) virtual
Subscribes to subject,type and specifies callback,userArg.
Parameters
subject Subject, can be regex
type Type, can be regex
cb Callback object to deliver messages to
userArg Passed to callback with message
cfg Subscription config object
Returns
Subscription handle, needed to unsubscribe
Exceptions
cMsgException if subscription fails, object was not initialized, or for some underlying domain's reason
Definition at line 1857 of file cMsgWrapper.cc.
References subscribe().
subscribe() [2/2]
void * cMsg::subscribe (const string & subject, const string & type, cMsgCallback * cb, void * userArg, const cMsgSubscriptionConfig * cfg = NULL) virtual
Subscribes to subject,type and specifies callback, userArg.
Parameters
subject Subject, can be regex
type Type, can be regex
cb Callback object to deliver messages to
userArg Passed to callback with message
cfg Subscription config object
Returns
Subscription handle, needed to unsubscribe
Exceptions
cMsgException if subscription fails, object was not initialized, or for some underlying domain's reason
Definition at line 1800 of file cMsgWrapper.cc.
Referenced by subscribe().
subscribeAndGet()
cMsgMessage * cMsg::subscribeAndGet (const string & subject, const string & type, const struct timespec * timeout = NULL) virtual
Subscribes to subject/type, returns one matching message, then unsubscribes.
Parameters
subject Subject, can be regex
type Type, can be regex
timeout Timeout
Returns
Matching message
Exceptions
cMsgException
Definition at line 2106 of file cMsgWrapper.cc.
subscriptionMessagesTotal()
int cMsg::subscriptionMessagesTotal (void * handle) virtual
Return the total number of messages passed to the given subscription's callback.
Parameters
handle Subscription handle
Returns
total number of messages passed to the given subscription's callback
Exceptions
cMsgException
Definition at line 1998 of file cMsgWrapper.cc.
subscriptionPause()
void cMsg::subscriptionPause (void * handle) virtual
Pause delivery of messages to the given subscription's callback.
Parameters
handle Subscription handle
Exceptions
cMsgException
Definition at line 1903 of file cMsgWrapper.cc.
subscriptionQueueClear()
void cMsg::subscriptionQueueClear (void * handle) virtual
Clear all messages from the given subscription callback's queue.
Parameters
handle Subscription handle
Exceptions
cMsgException
Definition at line 1949 of file cMsgWrapper.cc.
subscriptionQueueCount()
int cMsg::subscriptionQueueCount (void * handle) virtual
Return the number of messages currently in the given subscription callback's queue.
Parameters
handle Subscription handle
Returns
number of messages currently in the given subscription callback's queue
Exceptions
cMsgException
Definition at line 1973 of file cMsgWrapper.cc.
subscriptionQueueIsFull()
bool cMsg::subscriptionQueueIsFull (void * handle) virtual
Returns whether the given subscription callback's queue is full (true) or not.
Parameters
handle Subscription handle
Returns
boolean stating whether the given subscription callback's queue is full or not
Exceptions
cMsgException
Definition at line 2023 of file cMsgWrapper.cc.
subscriptionResume()
void cMsg::subscriptionResume (void * handle) virtual
Resume delivery of messages to the given subscription's callback if paused.
Parameters
handle Subscription handle
Exceptions
cMsgException
Definition at line 1926 of file cMsgWrapper.cc.
syncSend() [1/2]
int cMsg::syncSend (cMsgMessage & msg, const struct timespec * timeout = NULL) virtual
Synchronously sends message.
Parameters
msg Message to send
timeout Timeout
Exceptions
cMsgException
Definition at line 1754 of file cMsgWrapper.cc.
References cmsg::cMsgMessage::myMsgPointer.
Referenced by syncSend().
syncSend() [2/2]
int cMsg::syncSend (cMsgMessage * msg, const struct timespec * timeout = NULL) virtual
Synchronously sends message.
Parameters
msg Message to send
timeout Timeout
Exceptions
cMsgException
Definition at line 1779 of file cMsgWrapper.cc.
References syncSend().
unsubscribe()
void cMsg::unsubscribe (void * handle) virtual
Unsubscribes.
Parameters
handle Subscription handle
Exceptions
cMsgException
Definition at line 1872 of file cMsgWrapper.cc.
The documentation for this class was generated from the following files:
cMsg.hxx
cMsgWrapper.cc