# scons build file for cmsg
Import('env', 'binDir', 'archDir', 'execLibs', 'debugSuffix')

# list of files to compile (don't compile Channel Access files)
ccfileList = ['cMsgCommand.cc',
              'cMsgMonitor.cc',
              'cMsgPayloadTest.cc',
              'cMsgReceive.cc']
              
# If we store all compiled programs in a list and then
# install the list itself, for some unknown reason the
# whole variant library is copied into the install directory.
# So we do things individual file by individual file.

# compile and install
for fileName in ccfileList:
    compiledFile = env.Program(source  = fileName,
                               LIBS    = ['cmsgRegex'+debugSuffix,
                                          'cmsg'+debugSuffix,
                                          'cmsgxx'+debugSuffix] + execLibs,
                               LIBPATH = ['#src/regexp/'+archDir,
                                          '#src/libsrc/'+archDir,
                                          '#src/libsrc++/'+archDir],
                               CPPPATH = ['.', '#src/regexp', '#src/libsrc', '#src/libsrc++'])
    env.Alias('examples', env.Install(target = binDir, source = compiledFile))
