# scons build file for cmsg
Import('env', 'binDir', 'archDir', 'execLibs', 'debugSuffix')

# list of files to compile (don't compile Channel Access files)
ccfileList = ['cMsgCommand.cc',
              'cMsgMonitor.cc',
              'cMsgPayloadTest.cc',
              'cMsgReceive.cc',
              'cMsgExecutor.c']
              
# compile and install
for fileName in ccfileList:
    compiledFile = env.Program(source  = fileName,
                               LIBS    = ['cmsgRegex'+debugSuffix,
                                          'cmsg'+debugSuffix,
                                          'cmsgxx'+debugSuffix] + execLibs,
                               LIBPATH = ['#src/regexp/'+archDir,
                                          '#src/libsrc/'+archDir,
                                          '#src/libsrc++/'+archDir],
                               CPPPATH = ['.', '#src/regexp', '#src/libsrc', '#src/libsrc++'])
    env.Alias('install', env.Install(target = binDir, source = compiledFile))

