# scons build file for cMsg C++ library
Import('env', 'libInstallDir', 'incInstallDir', 'archIncInstallDir', 'debugSuffix')

fileList   = Glob('*.cc',  strings=True)
headerList = Glob('*.hxx', strings=True)

env.AppendUnique(CPPPATH = ['.', '#src/regexp', '#src/libsrc'])
cmsgxxLib = env.SharedLibrary(target = 'cmsgxx'+debugSuffix, source = fileList)
    
if 'install' in COMMAND_LINE_TARGETS:
    env.Alias("install", env.Install(target = [incInstallDir, archIncInstallDir], source = headerList))
    env.Alias("install", env.Install(target = libInstallDir, source = cmsgxxLib))
