# scons build file for cmsg
Import('env', 'incDir', 'libDir')

fileList = ['regcomp.c',
            'regerror.c',
            'regexec.c',
            'regfree.c']

regexpLib = env.SharedLibrary(target = 'cmsgRegex', source = fileList, CPPPATH = '.')
env.Alias("install", env.Install(target = incDir, source = 'regex.h'))
env.Alias("install", env.Install(target = libDir, source = regexpLib))
