# scons build file for cmsg
Import('env', 'incDir', 'libDir', 'tarfile')

libFiles = ['regcomp.c',
            'regerror.c',
            'regexec.c',
            'regfree.c']

env.AppendUnique(CPPPATH = '.')
regexpLib = env.SharedLibrary(target = 'cmsgRegex', source = libFiles)

env.Alias("install", env.Install(target = incDir, source = 'regex.h'))
env.Alias("install", env.Install(target = libDir, source = regexpLib))
